services:
  mysql:
    image: mysql:8.0
    container_name: event_finder_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: event_finder_db
      MYSQL_USER: event_finder_user
      MYSQL_PASSWORD: event_finder_password
    ports:
      - "8006:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  eventfinder-api:
    build:
      context: .
      dockerfile: ./EventFinder.API/Dockerfile
    container_name: eventfinder-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=event_finder_db;User=event_finder_user;Password=event_finder_password;"
    ports:
      - "8080:8080"
      - "8443:8443"

volumes:
  mysql_data: