services:
  postgres:
    image: postgres:15
    container_name: event_finder_postgres
    restart: always
    environment:
      POSTGRES_DB: event_finder_db
      POSTGRES_USER: event_finder_user
      POSTGRES_PASSWORD: event_finder_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U event_finder_user -d event_finder_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  eventfinder-api:
    build:
      context: .
      dockerfile: ./EventFinder.API/Dockerfile
    container_name: eventfinder-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=event_finder_db;Username=event_finder_user;Password=event_finder_password;"
    ports:
      - "8080:8080"
      - "8443:8443"

volumes:
  postgres_data: